"""Generate code_aster command (.comm) and run_aster export files.

Unit convention (mm-t-s): E [MPa], rho [t/mm^3], force [N], pressure [MPa],
gravity [mm/s^2], frequency [Hz].

Logical unit map (run_aster copies fort.<n> back for R entries):
  19  mesh.unv          (D)   IDEAS mesh from gmsh
  80  result.med        (R)   fields
  37  tables.txt        (R)   mass / reactions (block CSV)
  38  modes.csv         (R)   frequency table
  39  participation.csv (R)   effective-mass table
  40+ frf_p<i>_<c>.csv  (R)   FRF module+phase per probe component

Ordering and failure policy: the expensive result (the MED) is written FIRST,
because it is produced by IMPR_RESU, the most version-stable command here.
Every table afterwards is emitted inside `try/except` via _optional(), since a
.comm executes as Python and code_aster <EXCEPTION> errors are catchable.

This is deliberate. The first real modal run computed all ten modes and then
threw them away, because a table used NOM_PARA='NUME_ORDRE' (a MODE_MECA
publishes NUME_MODE) and the abort happened before the MED was written.
No single table may ever discard a completed solve again.
"""
from __future__ import annotations

from .materials import to_solver_units
from .meshing import group_name

G_MM = 9810.0  # standard gravity, mm/s^2

FRF_COMPONENTS = ("DX", "DY", "DZ")


def _fmt(x) -> str:
    return repr(float(x))


def _group_tuple(names) -> str:
    inner = ", ".join(f"'{n}'" for n in names)
    return f"({inner},)"


class CommBuild:
    def __init__(self):
        self.lines = []
        self.result_files = []   # (unit, filename)

    def w(self, s=""):
        self.lines.append(s)

    def text(self):
        return "\n".join(self.lines) + "\n"


def _env_sphere(b: CommBuild, name: str, xyz, r: float) -> None:
    b.w(f"mesh = DEFI_GROUP(reuse=mesh, MAILLAGE=mesh, CREA_GROUP_NO=_F(")
    b.w(f"    NOM='{name}', OPTION='ENV_SPHERE',")
    b.w(f"    POINT=({_fmt(xyz[0])}, {_fmt(xyz[1])}, {_fmt(xyz[2])}),")
    b.w(f"    RAYON={_fmt(r)}, PRECISION={_fmt(r)}))")


def _prelude(b: CommBuild, setup: dict, meta: dict, mesh_stats: dict,
             need_probes: bool, analysis: dict = None, ai: int = 1) -> None:
    bolts = _active_bolts(setup, mesh_stats)
    remotes = _active_remotes(analysis or {}, ai, mesh_stats)

    b.w("# Generated by Lattice — do not edit while a run is active")
    b.w("DEBUT(LANG='EN')")
    b.w()
    b.w("mesh = LIRE_MAILLAGE(FORMAT='IDEAS', UNITE=19)")
    b.w()
    b.w("mesh = DEFI_GROUP(reuse=mesh, MAILLAGE=mesh,")
    b.w("                  CREA_GROUP_NO=_F(TOUT_GROUP_MA='OUI'))")

    if need_probes:
        for i, p in enumerate(mesh_stats.get("probes", [])):
            r = max(p.get("snap_dist", 0.0) * 1e-3, 1e-6)
            _env_sphere(b, f"PROBE{i + 1}", p["node_xyz"], r)
    # bolt end nodes / remote points: exact coordinates from mesh time
    for br in bolts:
        _env_sphere(b, f"BN{br['index']}A", br["end_a"], 1e-5)
        _env_sphere(b, f"BN{br['index']}B", br["end_b"], 1e-5)
    for rr in remotes:
        _env_sphere(b, group_name("RPN", rr.get("analysis_index", ai),
                                  rr["load_index"]), rr["node"], 1e-5)
    b.w()

    beam_groups = ([f"BOLT{br['index']}" for br in bolts]
                   + [rr.get("group") or group_name("RPT", rr.get("analysis_index", ai),
                                                    rr["load_index"]) for rr in remotes])

    # model: explicit group lists — beams and solids carry different
    # modelisations, so TOUT='OUI' is no longer possible with beams present
    vol_groups = [f"V{s['tag']}" for s in meta.get("solids", [])]
    face_groups = mesh_stats.get("face_groups", [])
    if beam_groups:
        g3d = _group_tuple(vol_groups + list(face_groups))
        b.w("model = AFFE_MODELE(MAILLAGE=mesh, AFFE=(")
        b.w(f"    _F(GROUP_MA={g3d}, PHENOMENE='MECANIQUE', MODELISATION='3D'),")
        b.w(f"    _F(GROUP_MA={_group_tuple(beam_groups)}, PHENOMENE='MECANIQUE', MODELISATION='POU_D_T'),")
        b.w("))")
    else:
        b.w("model = AFFE_MODELE(MAILLAGE=mesh,")
        b.w("                    AFFE=_F(TOUT='OUI', PHENOMENE='MECANIQUE', MODELISATION='3D'))")
    b.w()

    # materials
    mats = {m["id"]: m for m in setup.get("materials", [])}
    assign = setup.get("assignments", {})
    mat_vars = {}
    for k, mid in sorted(assign.items()):
        if mid not in mats:
            raise ValueError(f"Solid {k} references unknown material '{mid}'")
        if mid not in mat_vars:
            u = to_solver_units(mats[mid])
            var = f"mat{len(mat_vars) + 1}"
            mat_vars[mid] = var
            b.w(f"{var} = DEFI_MATERIAU(ELAS=_F(E={_fmt(u['E'])}, NU={_fmt(u['NU'])}, RHO={_fmt(u['RHO'])}))")
    affes = []
    for k, mid in sorted(assign.items()):
        affes.append(f"_F(GROUP_MA=('V{int(k)}',), MATER={mat_vars[mid]})")
    if not affes:
        raise ValueError("No material assignments — assign a material to every solid before solving.")
    for br in bolts:
        cfg = br["cfg"]
        E = float(cfg.get("E_GPa", 210.0)) * 1000.0
        b.w(f"matb{br['index']} = DEFI_MATERIAU(ELAS=_F(E={_fmt(E)}, NU=0.3, RHO=7.85e-09))")
        affes.append(f"_F(GROUP_MA=('BOLT{br['index']}',), MATER=matb{br['index']})")
    if remotes:
        b.w("matrp = DEFI_MATERIAU(ELAS=_F(E=210000.0, NU=0.3, RHO=7.85e-09))")
        for rr in remotes:
            affes.append("_F(GROUP_MA=('%s',), MATER=matrp)" % (
                rr.get("group") or group_name("RPT", rr.get("analysis_index", ai), rr["load_index"])))
    b.w()
    b.w("chmat = AFFE_MATERIAU(MAILLAGE=mesh, AFFE=(")
    for a in affes:
        b.w(f"    {a},")
    b.w("))")
    b.w()

    # beam sections + spiders
    if beam_groups:
        b.w("cara = AFFE_CARA_ELEM(MODELE=model, POUTRE=(")
        for br in bolts:
            r = float(br["cfg"].get("d_mm", 8.0)) / 2.0
            b.w(f"    _F(GROUP_MA=('BOLT{br['index']}',), SECTION='CERCLE', "
                f"CARA='R', VALE={_fmt(r)}),")
        for rr in remotes:
            b.w("    _F(GROUP_MA=('%s',), SECTION='CERCLE', CARA='R', VALE=0.5)," % (
                rr.get("group") or group_name("RPT", rr.get("analysis_index", ai), rr["load_index"])))
        b.w("))")
        b.w()
        b.w("# RBE3 spiders: master nodes drive their face sets with a")
        b.w("# distributing (deformable) coupling, like Ansys 'Deformable' behavior")
        b.w("spider = AFFE_CHAR_MECA(MODELE=model, LIAISON_RBE3=(")
        for br in bolts:
            for side in ("A", "B"):
                b.w(f"    _F(GROUP_NO_MAIT='BN{br['index']}{side}',")
                b.w("       DDL_MAIT=('DX', 'DY', 'DZ', 'DRX', 'DRY', 'DRZ'),")
                b.w(f"       GROUP_NO_ESCL=('BF{side}{br['index']}',),")
                b.w("       DDL_ESCL=('DX-DY-DZ',), COEF_ESCL=(1.0,)),")
        for rr in remotes:
            b.w("    _F(GROUP_NO_MAIT='%s'," % group_name(
                "RPN", rr.get("analysis_index", ai), rr["load_index"]))
            b.w("       DDL_MAIT=('DX', 'DY', 'DZ', 'DRX', 'DRY', 'DRZ'),")
            b.w("       GROUP_NO_ESCL=('%s',)," % group_name(
                "LOA", rr.get("analysis_index", ai), rr["load_index"]))
            b.w("       DDL_ESCL=('DX-DY-DZ',), COEF_ESCL=(1.0,)),")
        b.w("))")
        b.w()

    # tie constraints (bonded, non-conformal)
    ties = [t for t in setup.get("ties", [])
            if t.get("slave_faces") and t.get("master_solid")]
    if ties:
        b.w("# tied (glued) face-to-volume constraints for non-conformal interfaces")
        b.w("tiec = AFFE_CHAR_MECA(MODELE=model, LIAISON_MAIL=(")
        for i, t in enumerate(ties):
            b.w(f"    _F(GROUP_MA_MAIT=('V{int(t['master_solid'])}',),")
            b.w(f"       GROUP_MA_ESCL=('TIE{i + 1}',), TYPE_RACCORD='MASSIF'),")
        b.w("))")
        b.w()

    b.constraint_charges = []
    if beam_groups:
        b.constraint_charges.append("spider")
    if ties:
        b.constraint_charges.append("tiec")
    b.has_bolts = bool(bolts)
    b.has_beams = bool(beam_groups)
    b.bolts = bolts
    b.remotes = remotes


def _active_bolts(setup: dict, mesh_stats: dict) -> list:
    """Join bolt setup entries with the geometric records from mesh time."""
    recs = {r.get("id"): r for r in mesh_stats.get("bolts", [])}
    out = []
    for bcfg in setup.get("bolts", []):
        rec = recs.get(bcfg.get("id"))
        if rec is None:
            continue
        out.append({**rec, "cfg": bcfg})
    if out and len(mesh_stats.get("bolts", [])) != len(setup.get("bolts", [])):
        raise ValueError("Mesh is older than the bolt setup — re-mesh before solving.")
    return out


def _active_remotes(analysis: dict, ai: int, mesh_stats: dict) -> list:
    """Remote loads of THIS analysis, joined with their mesh-time records."""
    recs = {r.get("id"): r for r in mesh_stats.get("remotes", [])}
    out = []
    for l in analysis.get("loads", []):
        if l.get("type") != "remote":
            continue
        rec = recs.get(l.get("id"))
        if rec is None:
            raise ValueError("Mesh is older than the remote-load setup — "
                             "re-mesh before solving.")
        out.append({**rec, "cfg": l})
    return out


def _cara_arg(b: CommBuild) -> str:
    return " CARA_ELEM=cara," if getattr(b, "has_beams", False) else ""


def _preload_charge(b: CommBuild) -> "str|None":
    """PRE_EPSI axial pre-strain per preloaded bolt: EPX = -F / (E*A) puts the
    shank in ~F of tension against a stiff joint."""
    import math
    items = []
    for br in getattr(b, "bolts", []):
        cfg = br["cfg"]
        F = float(cfg.get("preload_N") or 0.0)
        if F <= 0:
            continue
        E = float(cfg.get("E_GPa", 210.0)) * 1000.0
        A = math.pi * (float(cfg.get("d_mm", 8.0)) / 2.0) ** 2
        items.append((br["index"], -F / (E * A)))
    if not items:
        return None
    b.w("preload = AFFE_CHAR_MECA(MODELE=model, PRE_EPSI=(")
    for idx, eps in items:
        b.w(f"    _F(GROUP_MA=('BOLT{idx}',), EPX={_fmt(eps)}),")
    b.w("))")
    b.w()
    return "preload"


def _bolt_forces_out(b: CommBuild, result_var: str) -> None:
    """EFGE_ELNO on the beam ends -> per-bolt N/V/M table on unit 36."""
    if not getattr(b, "has_bolts", False):
        return
    beam_groups = _group_tuple([f"BOLT{br['index']}" for br in b.bolts])
    bolts = list(b.bolts)

    def bolt_block(x):
        x.w(f"{result_var} = CALC_CHAMP(reuse={result_var}, RESULTAT={result_var},")
        x.w(f"                CARA_ELEM=cara, GROUP_MA={beam_groups},")
        x.w("                CONTRAINTE=('EFGE_ELNO',))")
        for br in bolts:
            for side in ("A", "B"):
                x.w(f"bt{br['index']}{side} = POST_RELEVE_T(ACTION=_F(")
                x.w(f"    INTITULE='BOLT{br['index']}_{side}', OPERATION='EXTRACTION',")
                x.w(f"    RESULTAT={result_var}, NOM_CHAM='EFGE_ELNO',")
                x.w(f"    GROUP_NO='BN{br['index']}{side}', TOUT_CMP='OUI'))")
                x.w(f"IMPR_TABLE(TABLE=bt{br['index']}{side}, UNITE=36, "
                    f"FORMAT='TABLEAU', SEPARATEUR=',')")
        x.result_files.append((36, "bolt_forces.csv"))
    _optional(b, "bolt end forces", bolt_block)


def _supports(b: CommBuild, analysis: dict, ai: int) -> str:
    ddl_items, face_items = [], []
    for i, s in enumerate(analysis.get("supports", [])):
        if not s.get("faces"):
            continue
        g = group_name("SUP", ai, i + 1)
        stype = s.get("type", "fixed")
        if stype == "fixed":
            ddl_items.append(f"_F(GROUP_MA=('{g}',), DX=0.0, DY=0.0, DZ=0.0)")
        elif stype == "frictionless":
            # normal-only constraint = Ansys Frictionless Support / symmetry
            face_items.append(f"_F(GROUP_MA=('{g}',), DNOR=0.0)")
        else:  # prescribed displacement; None => leave DOF free
            comps = []
            for c, key in (("DX", "ux"), ("DY", "uy"), ("DZ", "uz")):
                v = s.get(key)
                if v is not None:
                    comps.append(f"{c}={_fmt(v)}")
            if comps:
                ddl_items.append(f"_F(GROUP_MA=('{g}',), {', '.join(comps)})")
    if not ddl_items and not face_items:
        raise ValueError(f"'{analysis.get('name', 'Analysis')}' has no support with "
                         "faces — add one under this analysis.")
    b.w("fix = AFFE_CHAR_MECA(MODELE=model,")
    if ddl_items:
        b.w("    DDL_IMPO=(")
        for it in ddl_items:
            b.w(f"        {it},")
        b.w("    ),")
    if face_items:
        b.w("    FACE_IMPO=(")
        for it in face_items:
            b.w(f"        {it},")
        b.w("    ),")
    b.w(")")
    b.w()
    return "fix"


def _loads(b: CommBuild, analysis: dict, ai: int, meta: dict, var: str = "loadc",
           harmonic: bool = False) -> "str|None":
    """Emit one AFFE_CHAR_MECA holding every load. Returns var name or None.
    harmonic=True skips body loads that make no sense as a harmonic
    excitation (rotation)."""
    import math
    force_items, pres_items, nodal_items, grav, rot = [], [], [], None, None
    areas = {f["tag"]: f["area"] for f in meta.get("faces", [])}
    for i, l in enumerate(analysis.get("loads", [])):
        t = l.get("type")
        g = group_name("LOA", ai, i + 1)
        if t == "force" and l.get("faces"):
            area = sum(areas.get(int(ft), 0.0) for ft in l["faces"])
            if area <= 0:
                raise ValueError(f"Load '{l.get('name', g)}': face area is zero")
            fx = float(l.get("fx", 0)) / area
            fy = float(l.get("fy", 0)) / area
            fz = float(l.get("fz", 0)) / area
            force_items.append(
                f"_F(GROUP_MA=('{g}',), FX={_fmt(fx)}, FY={_fmt(fy)}, FZ={_fmt(fz)})")
        elif t == "pressure" and l.get("faces"):
            pres_items.append(f"_F(GROUP_MA=('{g}',), PRES={_fmt(l.get('pressure', 0))})")
        elif t == "remote" and l.get("faces"):
            # applied at the RBE3 master node created at mesh time
            comps = []
            for c, key in (("FX", "fx"), ("FY", "fy"), ("FZ", "fz"),
                           ("MX", "mx"), ("MY", "my"), ("MZ", "mz")):
                v = float(l.get(key) or 0.0)
                if v != 0.0:
                    comps.append(f"{c}={_fmt(v)}")
            if comps:
                nodal_items.append(
                    f"_F(GROUP_NO=('{group_name('RPN', ai, i + 1)}',), {', '.join(comps)})")
        elif t == "gravity" and not harmonic:
            gdir = l.get("g", [0, 0, -1])
            n = math.sqrt(sum(c * c for c in gdir)) or 1.0
            gmag = float(l.get("g_mag", 1.0)) * G_MM
            grav = (gmag, [c / n for c in gdir])
        elif t == "rotation" and not harmonic:
            if rot is not None:
                raise ValueError("Only one rotational-velocity load is supported.")
            ax = l.get("axis", [0, 0, 1])
            n = math.sqrt(sum(c * c for c in ax)) or 1.0
            omega = float(l.get("rpm", 0.0)) * 2.0 * math.pi / 60.0
            ctr = l.get("center", [0, 0, 0])
            rot = (omega, [c / n for c in ax], ctr)
    if not (force_items or pres_items or nodal_items or grav or rot):
        return None
    b.w(f"{var} = AFFE_CHAR_MECA(MODELE=model,")
    if force_items:
        b.w("    FORCE_FACE=(")
        for it in force_items:
            b.w(f"        {it},")
        b.w("    ),")
    if pres_items:
        b.w("    PRES_REP=(")
        for it in pres_items:
            b.w(f"        {it},")
        b.w("    ),")
    if nodal_items:
        b.w("    FORCE_NODALE=(")
        for it in nodal_items:
            b.w(f"        {it},")
        b.w("    ),")
    if grav:
        gmag, d = grav
        b.w(f"    PESANTEUR=_F(GRAVITE={_fmt(gmag)}, DIRECTION=({_fmt(d[0])}, {_fmt(d[1])}, {_fmt(d[2])})),")
    if rot:
        omega, ax, ctr = rot
        b.w(f"    ROTATION=_F(VITESSE={_fmt(omega)},")
        b.w(f"                AXE=({_fmt(ax[0])}, {_fmt(ax[1])}, {_fmt(ax[2])}),")
        b.w(f"                CENTRE=({_fmt(ctr[0])}, {_fmt(ctr[1])}, {_fmt(ctr[2])})),")
    b.w(")")
    b.w()
    return var


def _support_groups(analysis: dict, ai: int) -> list:
    return [group_name("SUP", ai, i + 1)
            for i, s in enumerate(analysis.get("supports", [])) if s.get("faces")]


# --------------------------------------------------------------------------

def write_static(setup: dict, meta: dict, mesh_stats: dict, cfg: dict,
                 analysis: dict = None, ai: int = 1) -> CommBuild:
    b = CommBuild()
    _prelude(b, setup, meta, mesh_stats, need_probes=False, analysis=analysis, ai=ai)
    fix = _supports(b, analysis, ai)
    load = _loads(b, analysis, ai, meta)
    preload = _preload_charge(b)
    if load is None and preload is None:
        raise ValueError("Static analysis needs at least one load (force, pressure, gravity, or bolt preload).")

    charges = [fix] + b.constraint_charges + ([load] if load else []) + ([preload] if preload else [])
    excit = ", ".join(f"_F(CHARGE={c})" for c in charges)
    b.w("res = MECA_STATIQUE(MODELE=model, CHAM_MATER=chmat,")
    b.w(f"                    EXCIT=({excit},),{_cara_arg(b)}")
    b.w("                    SOLVEUR=_F(METHODE='MUMPS'))")
    b.w()
    vol_restrict = ""
    if getattr(b, "has_beams", False):
        # stress recovery is a solid-element concept; beams get EFGE below
        vol_restrict = "                 GROUP_MA=%s,\n" % _group_tuple(
            ["V%d" % s["tag"] for s in meta.get("solids", [])])
    b.w(f"res = CALC_CHAMP(reuse=res, RESULTAT=res,{_cara_arg(b)}")
    if vol_restrict:
        b.w(vol_restrict.rstrip("\n"))
    b.w("                 CONTRAINTE=('SIGM_NOEU',),")
    b.w("                 CRITERES=('SIEQ_NOEU',),")
    b.w("                 FORCE=('REAC_NODA',))")
    b.w()
    vol_groups = _group_tuple(["V%d" % s["tag"] for s in meta.get("solids", [])])
    b.w("IMPR_RESU(FORMAT='MED', UNITE=80, RESU=_F(")
    b.w("    RESULTAT=res, NOM_CHAM=('DEPL', 'SIEQ_NOEU', 'SIGM_NOEU'),")
    b.w(f"    GROUP_MA={vol_groups}))")
    b.result_files.append((80, "result.med"))
    b.w()
    _bolt_forces_out(b, "res")
    groups = _support_groups(analysis, ai)

    def reactions(x):
        x.w("rtab = POST_RELEVE_T(ACTION=_F(INTITULE='REACTIONS', OPERATION='EXTRACTION',")
        x.w("                               RESULTANTE=('DX', 'DY', 'DZ'),")
        x.w("                               RESULTAT=res, NOM_CHAM='REAC_NODA',")
        x.w(f"                               GROUP_NO={_group_tuple(groups)}))")
        x.w("IMPR_TABLE(TABLE=rtab, UNITE=37, FORMAT='TABLEAU', SEPARATEUR=',')")
        x.result_files.append((37, "tables.txt"))
    _optional(b, "reaction forces", reactions)

    b.w("FIN()")
    return b


def _modal_core(b: CommBuild, setup: dict, cfg: dict, fix: str) -> None:
    """ASSEMBLAGE + CALC_MODES; leaves `modes`, `MK`, `MM`, `nddl` defined.
    Bolt spiders and ties are constraint charges: they belong in the
    assembled operators so beams and glued interfaces carry stiffness in
    modal/harmonic too. Preload does not enter (linear, no stress stiffening)."""
    charges = ", ".join([fix] + b.constraint_charges)
    b.w(f"ASSEMBLAGE(MODELE=model, CHAM_MATER=chmat, CHARGE=({charges},),")
    if getattr(b, "has_beams", False):
        b.w("           CARA_ELEM=cara,")
    b.w("           NUME_DDL=CO('nddl'),")
    b.w("           MATR_ASSE=(_F(MATRICE=CO('MK'), OPTION='RIGI_MECA'),")
    b.w("                      _F(MATRICE=CO('MM'), OPTION='MASS_MECA')))")
    b.w()
    band = cfg.get("band")
    if band:
        b.w("modes = CALC_MODES(MATR_RIGI=MK, MATR_MASS=MM, OPTION='BANDE',")
        b.w(f"                   CALC_FREQ=_F(FREQ=({_fmt(band[0])}, {_fmt(band[1])})),")
    else:
        n = int(cfg.get("n_modes", 10))
        b.w("modes = CALC_MODES(MATR_RIGI=MK, MATR_MASS=MM, OPTION='PLUS_PETITE',")
        b.w(f"                   CALC_FREQ=_F(NMAX_FREQ={n}),")
    b.w("                   SOLVEUR_MODAL=_F(METHODE='SORENSEN'),")
    b.w("                   SOLVEUR=_F(METHODE='MUMPS'),")
    b.w("                   VERI_MODE=_F(STOP_ERREUR='NON'))")
    b.w()


def _optional(b: CommBuild, comment: str, body) -> None:
    """Emit a block that must never abort the run.

    A .comm is executed as Python, so a catchable code_aster <EXCEPTION>
    (a wrong NOM_PARA, a parameter a given version doesn't publish) can be
    contained. Without this, one unavailable table throws away results that
    were already computed — which is exactly what happened to the first real
    modal run.
    """
    b.w(f"# optional: {comment}")
    b.w("try:")
    inner = CommBuild()
    body(inner)
    for line in inner.lines:
        b.w(f"    {line}" if line else "")
    b.result_files.extend(inner.result_files)
    b.w("except Exception as _e:")
    b.w(f"    print('Lattice: skipped {comment} —', _e)")
    b.w()


def write_modal(setup: dict, meta: dict, mesh_stats: dict, cfg: dict,
                analysis: dict = None, ai: int = 1) -> CommBuild:
    b = CommBuild()
    _prelude(b, setup, meta, mesh_stats, need_probes=False, analysis=analysis, ai=ai)
    fix = _supports(b, analysis, ai)
    _modal_core(b, setup, cfg, fix)

    # Mode shapes FIRST: IMPR_RESU is the most stable command here and the
    # result is the expensive one. Tables come after, each individually
    # non-fatal, so a version quirk in a table can't discard the modes.
    b.w("IMPR_RESU(FORMAT='MED', UNITE=80, RESU=_F(RESULTAT=modes, NOM_CHAM='DEPL'))")
    b.result_files.append((80, "result.med"))
    b.w()

    # MODE_MECA numbers modes with NUME_MODE (NUME_ORDRE does not exist on it)
    def freqs(x):
        x.w("ftab = RECU_TABLE(CO=modes, NOM_PARA=('NUME_MODE', 'FREQ'))")
        x.w("IMPR_TABLE(TABLE=ftab, UNITE=38, FORMAT='TABLEAU', SEPARATEUR=',')")
        x.result_files.append((38, "modes.csv"))
    _optional(b, "frequency table", freqs)

    def mass(x):
        x.w("mtab = POST_ELEM(MODELE=model, CHAM_MATER=chmat, MASS_INER=_F(TOUT='OUI'))")
        x.w("IMPR_TABLE(TABLE=mtab, UNITE=37, FORMAT='TABLEAU', SEPARATEUR=',')")
        x.result_files.append((37, "tables.txt"))
    _optional(b, "model mass", mass)

    def part(x):
        x.w("ptab = RECU_TABLE(CO=modes, NOM_PARA=('NUME_MODE', 'FREQ', 'MASS_GENE',")
        x.w("                  'MASS_EFFE_UN_DX', 'MASS_EFFE_UN_DY', 'MASS_EFFE_UN_DZ'))")
        x.w("IMPR_TABLE(TABLE=ptab, UNITE=39, FORMAT='TABLEAU', SEPARATEUR=',')")
        x.result_files.append((39, "participation.csv"))
    _optional(b, "effective mass table", part)

    b.w("FIN()")
    return b


def write_harmonic(setup: dict, meta: dict, mesh_stats: dict, cfg: dict,
                   analysis: dict = None, ai: int = 1) -> CommBuild:
    """Modal-superposition harmonic response.

    The modal basis is sized automatically: band [0, 1.6 * f_max] so
    truncation above the sweep is acceptable for displacement FRFs.
    """
    import math

    f0 = float(cfg.get("f_min", 20.0))
    f1 = float(cfg.get("f_max", 2000.0))
    nstep = int(cfg.get("n_steps", 200))
    spacing = cfg.get("spacing", "log")
    zeta = float(cfg.get("damping", 0.02))
    if f1 <= f0 or f0 <= 0:
        raise ValueError("Harmonic range must satisfy 0 < f_min < f_max")

    if spacing == "log":
        freqs = [f0 * (f1 / f0) ** (i / (nstep - 1)) for i in range(nstep)]
    else:
        freqs = [f0 + (f1 - f0) * i / (nstep - 1) for i in range(nstep)]

    field_freqs = cfg.get("field_freqs") or []
    field_freqs = sorted({round(float(f), 6) for f in field_freqs if f0 <= float(f) <= f1})

    # Excitation: forces defined in the tree, or rigid-base acceleration.
    base = None
    if cfg.get("excitation") == "base":
        d = cfg.get("base_dir", [0.0, 0.0, 1.0])
        n = math.sqrt(sum(c * c for c in d)) or 1.0
        base = {"dir": [c / n for c in d],
                "accel": float(cfg.get("base_g", 1.0)) * G_MM}   # g -> mm/s^2

    b = CommBuild()
    _prelude(b, setup, meta, mesh_stats, need_probes=True, analysis=analysis, ai=ai)
    fix = _supports(b, analysis, ai)
    load = None
    if base is None:
        load = _loads(b, analysis, ai, meta, harmonic=True)
        if load is None:
            raise ValueError("Harmonic analysis needs a load to excite the structure, "
                             "or set excitation to base acceleration.")
    if not mesh_stats.get("probes"):
        raise ValueError("Harmonic analysis needs at least one probe — "
                         "response is extracted there.")

    modal_cfg = {"band": [0.0, 1.6 * f1]}
    _modal_core(b, setup, modal_cfg, fix)

    def hfreqs(x):
        x.w("ftab = RECU_TABLE(CO=modes, NOM_PARA=('NUME_MODE', 'FREQ'))")
        x.w("IMPR_TABLE(TABLE=ftab, UNITE=38, FORMAT='TABLEAU', SEPARATEUR=',')")
        x.result_files.append((38, "modes.csv"))
    _optional(b, "modal basis table", hfreqs)
    cara_kw = " CARA_ELEM=cara," if getattr(b, "has_beams", False) else ""
    if base is not None:
        d = base["dir"]
        b.w("# Base (support) excitation: CALC_CHAR_SEISME builds the -M.d")
        b.w("# inertial load for a rigid base moving as one body. Response is")
        b.w("# RELATIVE to the base — absolute motion adds the base term back.")
        b.w("fas = CALC_CHAR_SEISME(MATR_MASS=MM, MONO_APPUI='OUI',")
        b.w(f"                       DIRECTION=({_fmt(d[0])}, {_fmt(d[1])}, {_fmt(d[2])}))")
    else:
        b.w(f"vel = CALC_VECT_ELEM(OPTION='CHAR_MECA', CHARGE=({load},),{cara_kw} CHAM_MATER=chmat)")
        b.w("fas = ASSE_VECTEUR(VECT_ELEM=vel, NUME_DDL=nddl)")
    b.w()
    b.w("PROJ_BASE(BASE=modes, STOCKAGE='PLEIN',")
    b.w("          MATR_ASSE_GENE=(_F(MATRICE=CO('KG'), MATR_ASSE=MK),")
    b.w("                          _F(MATRICE=CO('MG'), MATR_ASSE=MM)),")
    b.w("          VECT_ASSE_GENE=(_F(VECTEUR=CO('FG'), VECT_ASSE=fas, TYPE_VECT='FORC'),))")
    b.w()
    vals = ", ".join(_fmt(f) for f in freqs)
    b.w(f"lfr = DEFI_LIST_REEL(VALE=({vals},))")
    b.w()
    coef = base["accel"] if base else 1.0
    b.w("dyng = DYNA_VIBRA(TYPE_CALCUL='HARM', BASE_CALCUL='GENE',")
    b.w("                  MATR_MASS=MG, MATR_RIGI=KG, LIST_FREQ=lfr,")
    b.w(f"                  AMOR_MODAL=_F(AMOR_REDUIT=({_fmt(zeta)},)),")
    b.w(f"                  EXCIT=(_F(VECT_ASSE_GENE=FG, COEF_MULT={_fmt(coef)}),))")
    b.w()

    probes = mesh_stats.get("probes", [])
    unit = 40
    for i, _p in enumerate(probes):
        for c in FRF_COMPONENTS:
            b.w(f"f{i}{c} = RECU_FONCTION(RESU_GENE=dyng, NOM_CHAM='DEPL',")
            b.w(f"    NOM_CMP='{c}', GROUP_NO='PROBE{i + 1}')")
            b.w(f"m{i}{c} = CALC_FONCTION(EXTRACTION=_F(FONCTION=f{i}{c}, PARTIE='MODULE'))")
            b.w(f"p{i}{c} = CALC_FONCTION(EXTRACTION=_F(FONCTION=f{i}{c}, PARTIE='PHASE'))")
            b.w(f"IMPR_FONCTION(FORMAT='TABLEAU', UNITE={unit}, SEPARATEUR=',',")
            b.w(f"    COURBE=(_F(FONCTION=m{i}{c}), _F(FONCTION=p{i}{c})))")
            b.result_files.append((unit, f"frf_p{i + 1}_{c.lower()}.csv"))
            unit += 1
            b.w()

    if field_freqs:
        fv = ", ".join(_fmt(f) for f in field_freqs)
        b.w("dynp = REST_GENE_PHYS(RESU_GENE=dyng, NOM_CHAM='DEPL',")
        b.w(f"                      FREQ=({fv},), INTERPOL='LIN')")
        b.w("IMPR_RESU(FORMAT='MED', UNITE=80, RESU=(")
        b.w("    _F(RESULTAT=dynp, NOM_CHAM='DEPL', PARTIE='REEL'),")
        b.w("    _F(RESULTAT=dynp, NOM_CHAM='DEPL', PARTIE='IMAG')))")
        b.result_files.append((80, "result.med"))
        b.w()

    b.w("FIN()")
    return b


# --------------------------------------------------------------------------

def write_random(setup: dict, meta: dict, mesh_stats: dict, cfg: dict,
                 analysis: dict = None, ai: int = 1) -> CommBuild:
    """Random vibration = a unit-g base sweep spanning the input spectrum.

    Driving with exactly 1 g makes the exported FRF read directly as
    transmissibility, and the response PSD is then |T|^2 * PSD_in, integrated
    in random_vib.py. That keeps the solver side identical to the harmonic
    case which is already proven, instead of relying on a separate random
    operator chain.
    """
    spec = cfg.get("spec") or []
    pts = sorted((float(a), float(b)) for a, b in spec if float(a) > 0)
    if len(pts) < 2:
        raise ValueError("Random vibration needs at least two PSD breakpoints.")
    f0, f1 = pts[0][0], pts[-1][0]
    hcfg = {
        **cfg,
        "excitation": "base",
        "base_g": 1.0,                      # unit input => transmissibility
        "f_min": f0, "f_max": f1,
        "spacing": "log",
        "n_steps": int(cfg.get("n_steps", 600)),
        "field_freqs": cfg.get("field_freqs") or [],
    }
    return write_harmonic(setup, meta, mesh_stats, hcfg, analysis, ai)


WRITERS = {"static": write_static, "modal": write_modal,
           "harmonic": write_harmonic, "random": write_random}


def build_run(analysis: dict, setup: dict, meta: dict, mesh_stats: dict,
              solver_cfg) -> "tuple[str, str]":
    """Returns (comm_text, export_text)."""
    atype = analysis.get("type")
    if atype not in WRITERS:
        raise ValueError(f"Unknown analysis type: {atype}")
    if len(mesh_stats.get("probes", [])) > 6:
        raise ValueError("At most 6 probes are supported (logical unit budget).")
    ai = 1 + next((i for i, a in enumerate(setup.get("analyses", []))
                   if a.get("id") == analysis.get("id")), 0)
    b = WRITERS[atype](setup, meta, mesh_stats, analysis.get("config", {}), analysis, ai)

    exp = [
        "P actions make_etude",
        f"P memory_limit {int(solver_cfg.memory_mb)}",
        f"P time_limit {int(solver_cfg.time_limit_s)}",
        f"P ncpus {int(solver_cfg.ncpus)}",
        "P mpi_nbcpu 1",
        "F comm run.comm D 1",
        "F libr mesh.unv D 19",
    ]
    seen = set()
    for unit, fname in b.result_files:
        if unit in seen:
            continue
        seen.add(unit)
        exp.append(f"F libr {fname} R {unit}")
    exp.append("F mess run.mess R 6")
    return b.text(), "\n".join(exp) + "\n"
